### ISSUE TITLE
fekit registry 无法访问

### ISSUE THREAD

**Issue by zhouylgithub** [rinh/fekit#108]
http://l-registry.fe.dev.cn6.qunar.com:3300/

怎么无法访问？ 都ping不通？希望能有人解答？

**Comment by zhouylgithub** [comment]
http://l-registry.fe.dev.cn6.qunar.com:3300/

怎么无法访问？ 都ping不通？希望能有人解答？

**Comment by yashiro1899** [comment]
这是内网地址，在内网环境可以正常使用

**Comment by zhouylgithub** [comment]
我想使用avalon 和 oniui 该怎么配置这个地址，或者有没有什么方法可以无需配置此项
