### ISSUE TITLE
#54 的修正会引发新的问题

### ISSUE THREAD

**Issue by netwjx** [rinh/fekit#76]
#54 的修正会引发新的问题

`foo.scss`

```scss
.foo{
    .bar {
        @import "bar";
     }
}
```

`_bar.scss`

```scss
a {
    color: red;
}
```

以  `http://localhost/prd/styles/foo.css` 访问

```css
@import url('http://localhost/prd/styles/foo.scss?d3bfe8175baf3524');
```

这时 sass.coffee:行8  MAP 已经被填充满了

再访问 `http://localhost/prd/styles/foo.scss?d3bfe8175baf3524` 发现内容并不包括 `_bar.scss`

其次, 上述代码中的 `@import` 意思是 `_bar.scss` 中的所有选择器 自动加上 `.foo .bar` 的前缀, 这种场景不能去重

P.S. Stylus原生支持 require

**Comment by yashiro1899** [comment]
新版本已修复
