### ISSUE TITLE
util.coffee   判断绝对路径的正则表达式有问题。

### ISSUE THREAD

**Issue by honchy** [rinh/fekit#84]
is_absolute_path: ( path ) ->
        return ( process.platform is "win32" and path.match(/^[a-zA-Z]:(\\|\/)?$/) ) or path.charAt(0) is "/"

/^[a-zA-Z]:(\\|\/)?$/  这种表达式并不能够匹配形如：D:\github\honchy\test\page\index.vm 这种形式的路径。

**Comment by yashiro1899** [comment]
已经修复
