### ISSUE TITLE
velocity 模板中注入环境参数

### ISSUE THREAD

**Issue by honchy** [rinh/fekit#93]
场景是这样的。vm模板中需要写入link链接，而这些链接在本地，dev和beta，prd环境都是不一致的，因此希望能够在根据运行的环境不同，使用不同配置的link链接。
也就是说，针对本地，dev，beta，prd写四个不同link配置，然后希望vm总能够读取这些配置，这样就避免写死link带来的测试问题。

**Comment by yashiro1899** [comment]
beta 和 prd 上面的模板并不是由 fekit 编译

**Comment by yashiro1899** [comment]
已经支持
